# Generated by Django 3.1.1 on 2020-11-02 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201101_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='nombre_completo',
            new_name='Recibe_nombre',
        ),
        migrations.RemoveField(
            model_name='detalle',
            name='precio',
        ),
    ]
