# Generated by Django 3.1.1 on 2020-11-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201101_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='cant',
            field=models.IntegerField(default=1),
        ),
    ]
